# Generated by Django 5.2.3 on 2025-06-29 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cca', '0006_remove_ccamember_emergency_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organizer', models.TextField(blank=True, help_text='Optional if organized by a club', max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.TextField(blank=True, max_length=255)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('registration_deadline', models.DateTimeField()),
                ('is_public', models.BooleanField(default=True, help_text='Is this event open to only cca members?')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('contact_point', models.TextField(blank=True, help_text='Contact point for the event', max_length=255)),
                ('cca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cca.cca')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_registration_fee', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='attending', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
