# Generated by Django 5.2.3 on 2025-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_cca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='status',
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is this event open to everyone?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='paid_registration_fee',
            field=models.BooleanField(default=False),
        ),
    ]
