# Generated by Django 5.2.3 on 2025-07-17 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_eventparticipant_status_alter_event_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an event poster', max_length=255, null=True, verbose_name='image'),
        ),
    ]
