# Generated by Django 5.2.3 on 2025-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_organizer_event_admins_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='paid_registration_fee',
        ),
    ]
