# Generated by Django 5.2.3 on 2025-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_date_alter_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (leave blank for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted')], default='na', max_length=10),
        ),
    ]
