# Generated by Django 5.2.3 on 2025-07-26 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('training_reminder', 'Training Reminder'), ('event_registration', 'Event Registration'), ('match_update', 'Match Update'), ('cca_announcement', 'CCA Announcement'), ('tournament_update', 'Tournament Update'), ('merch_update', 'Merchandise Update')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_reminders', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('event_updates', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('match_updates', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('cca_announcements', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('reminder_hours_before', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
