# Generated by Django 5.2.3 on 2025-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('training_reminder', 'Training Reminder'), ('event_update', 'Event Update'), ('match_update', 'Match Update'), ('cca_announcement', 'CCA Announcement'), ('tournament_update', 'Tournament Update'), ('merch_update', 'Merchandise Update')], max_length=50),
        ),
    ]
