# Generated by Django 5.2.3 on 2025-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='merch_updates',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='tournament_updates',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
