# Generated by Django 5.2.3 on 2025-07-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotificationpreference_merch_updates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationpreference',
            old_name='match_updates',
            new_name='matchmaking_updates',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='reminder_hours_before',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('training_reminder', 'Training Reminder'), ('event_update', 'Event Update'), ('matchmaking_update', 'Matchmaking Update'), ('cca_announcement', 'CCA Announcement'), ('tournament_update', 'Tournament Update'), ('merch_update', 'Merchandise Update')], max_length=50),
        ),
    ]
