# Generated by Django 5.2.3 on 2025-07-29 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_match_updates_usernotificationpreference_matchmaking_updates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('training_reminder', 'Training Reminder'), ('event_update', 'Event Update'), ('matchmaking_update', 'Matchmaking Update'), ('cca_announcement', 'CCA Announcement'), ('tournament_update', 'Tournament Update'), ('merch_update', 'Merchandise Update')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent', 'scheduled_for'], name='notificatio_is_sent_0db5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at', 'is_read'], name='notificatio_created_12ba5b_idx'),
        ),
    ]
