# Generated by Django 5.2.3 on 2025-06-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sport', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('player', 'Player'), ('admin', 'Administrator')], default='player', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='lobbies', through='matchmaking.LobbyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
