# Generated by Django 5.2.3 on 2025-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_lobby_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
