# Generated by Django 5.2.3 on 2025-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_lobby_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='open_lobby',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
