# Generated by Django 5.2.3 on 2025-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_lobby_open_lobby_lobby_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
