# Generated by Django 5.2.3 on 2025-06-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_lobby_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
