# Generated by Django 5.2.3 on 2025-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_alter_lobby_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
