# Generated by Django 5.2.3 on 2025-07-17 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload a product image', max_length=255, verbose_name='image'),
        ),
    ]
