# Generated by Django 5.2.3 on 2025-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsport',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('coed', 'Coed')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
