# Generated by Django 5.2.3 on 2025-06-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentsport_gender_alter_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tournamentsport',
            new_name='tournament_sport',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentsport'),
            preserve_default=False,
        ),
    ]
