# Generated by Django 5.2.3 on 2025-07-29 04:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_tournamentsport_team_tournament_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a team logo', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a team member photo', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a tournament logo', max_length=255, null=True, verbose_name='image'),
        ),
    ]
