# Generated by Django 5.2.1 on 2025-06-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo for the CCA', null=True, upload_to='cca_logos')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telegram', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CCAMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cca.cca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cca',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ccas', through='cca.CCAMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('max_participants', models.PositiveIntegerField(default=30)),
                ('note', models.TextField(blank=True)),
                ('cca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cca.cca')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled'), ('na', 'Not Applicable')], default='na', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cca.ccamember')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cca.trainingsession')),
            ],
        ),
    ]
