# Generated by Django 5.2.1 on 2025-06-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccamember',
            name='position',
            field=models.CharField(choices=[('member', 'Member'), ('committee', 'Committee')], default='na', max_length=10),
        ),
        migrations.AlterField(
            model_name='ccamember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
