# Generated by Django 5.2.1 on 2025-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0002_ccamember_position_alter_ccamember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccamember',
            name='position',
            field=models.CharField(choices=[('member', 'Member'), ('committee', 'Committee')], default='member', max_length=10),
        ),
    ]
