# Generated by Django 5.2.1 on 2025-06-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0003_alter_ccamember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccamember',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
