# Generated by Django 5.2.3 on 2025-06-26 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0004_alter_ccamember_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
