# Generated by Django 5.2.3 on 2025-06-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0005_attendance_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccamember',
            name='emergency_contact',
        ),
    ]
