# Generated by Django 5.2.3 on 2025-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0006_remove_ccamember_emergency_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cca',
            name='contact_telegram',
        ),
        migrations.AddField(
            model_name='cca',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page of the CCA'),
        ),
        migrations.AddField(
            model_name='cca',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile of the CCA'),
        ),
        migrations.AddField(
            model_name='cca',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cca',
            name='website',
            field=models.URLField(blank=True, help_text='Official website of the CCA'),
        ),
        migrations.AlterField(
            model_name='cca',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
