# Generated by Django 5.2.3 on 2025-06-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0007_remove_cca_contact_telegram_cca_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cca',
            name='telegram_group',
        ),
    ]
