# Generated by Django 5.2.3 on 2025-07-17 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0008_remove_cca_telegram_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cca',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a cca logo', max_length=255, null=True, verbose_name='image'),
        ),
    ]
