<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-24 16:02

import django.core.validators
import users.models
from django.db import migrations, models
=======
# Generated by Django 4.2.21 on 2025-06-09 15:05

import django.core.validators
from django.db import migrations, models
import users.models
>>>>>>> 9a714d0 (Save local work before rebase)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, JPEG, PNG only)', null=True, upload_to=users.models.user_profile_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
