# Generated by Django 5.2.1 on 2025-06-29 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
