# Generated by Django 5.2.3 on 2025-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
